### ISSUE TITLE
✨ [新功能] 支持用户修改密码

### ISSUE THREAD

**Issue by devlivecommunity** [devlive-community/infosphere#14]
### 贡献准则

- [X] 我已阅读 [贡献指南](https://github.com/devlive-community/incubator-infosphere/blob/dev/CONTRIBUTING.md) 并完全同意

### 我想提出一个想法并检查了一下 ...

- [ ] ... 据我所知，我的想法不会破坏其他用户的东西
- [ ] ... 文档没有提到任何关于我的想法
- [ ] ... 没有与我的想法相关的未解决或已关闭的问题

### 受影响的模块

新功能 (默认)

### 描述

支持用户修改密码

**Comment by qianmoQ** [comment]
Stale issue message
