### ISSUE TITLE
docker  部署后无法登录，浏览器显示未与服务器建立链接

### ISSUE THREAD

**Issue by hfw99** [devlive-community/infosphere#42]
浏览器报错：无法建立到 127.0.0.1:9099 服务器的连接

docker ps
CONTAINER ID   IMAGE                   COMMAND               CREATED         STATUS         PORTS                                       NAMES
cc1a80eb3ade   devliveorg/infosphere   "sh ./bin/debug.sh"   3 minutes ago   Up 5 seconds   0.0.0.0:9099->9099/tcp, :::9099->9099/tcp   infosphere

**Comment by qianmoQ** [comment]
Stale issue message

**Comment by qianmoQ** [comment]
> 浏览器报错：无法建立到 127.0.0.1:9099 服务器的连接
> 
> docker ps CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES cc1a80eb3ade devliveorg/infosphere "sh ./bin/debug.sh" 3 minutes ago Up 5 seconds 0.0.0.0:9099->9099/tcp, :::9099->9099/tcp infosphere

替换 127.0.0.1 为具体的 IP 服务器地址即可
