### ISSUE TITLE
🐛 [Bug] 在线DEMO打不开

### ISSUE THREAD

**Issue by zeenpower** [devlive-community/infosphere#85]
### 贡献准则

- [X] 我已阅读 [贡献指南](https://github.com/devlive-community/incubator-infosphere/blob/dev/CONTRIBUTING.md) 并完全同意

### 我发现了一个错误并检查了它 ...

- [X] ... `服务端` 或 `Web端` 不会出现此问题
- [X] ... 文档没有提到任何关于我的问题
- [ ] ... 没有与我的问题相关的未解决或已关闭的问题

### 受影响的模块

其他模块

### 描述

在线DEMO网址：http://try.infosphere.devlive.org/
无法打开，服务器报502错误

### 包版本

- Java 版本: `java --version`
- 软件包版本: `./mvnw -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.help=INFO | tail -1`

### 系统信息

- 操作系统: MacOS 15.0.1 (24A348)
- 浏览器: Chrome 129.0.6668.90

**Comment by qianmoQ** [comment]
感谢反馈已经修复
